package com.kurt.motoshop;

import android.app.*;import android.os.*;import android.graphics.Color;import android.graphics.drawable.*;import android.view.*;import android.widget.*;import java.util.*;

public class MainActivity extends Activity {
    LinearLayout root, body, list; android.content.SharedPreferences db; final int BG=Color.rgb(5,6,8), PANEL=Color.rgb(13,15,19), WHITE=Color.WHITE, MUTED=Color.rgb(170,175,185), RED=Color.rgb(255,30,45), GREEN=Color.rgb(25,220,95), BLUE=Color.rgb(30,145,255), ORANGE=Color.rgb(255,145,25);
    int dp(int x){return (int)(x*getResources().getDisplayMetrics().density+.5f);} 
    TextView t(String s,float z,int c){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(c);v.setGravity(Gravity.CENTER_VERTICAL);return v;}
    GradientDrawable g(int c,int r,int sw,int sc){GradientDrawable x=new GradientDrawable();x.setColor(c);x.setCornerRadius(dp(r));if(sw>0)x.setStroke(dp(sw),sc);return x;}
    LinearLayout col(){LinearLayout x=new LinearLayout(this);x.setOrientation(LinearLayout.VERTICAL);return x;}
    @Override public void onCreate(Bundle b){super.onCreate(b);db=getSharedPreferences("kurt",MODE_PRIVATE);dashboard();}
    void shell(String title){root=col();root.setBackgroundColor(BG);LinearLayout top=new LinearLayout(this);top.setGravity(Gravity.CENTER_VERTICAL);top.setPadding(dp(16),dp(7),dp(12),dp(5));
      TextView menu=t("☰",29,WHITE);menu.setGravity(Gravity.CENTER);menu.setOnClickListener(v->drawer());top.addView(menu,new LinearLayout.LayoutParams(dp(52),dp(62)));
      LinearLayout brand=col();TextView a=t("KURT MOTOSHOP",22,WHITE);a.setTypeface(null,1);TextView b=t("V.1   •   RIDE  |  BUILD  |  TRUST",9,RED);brand.addView(a);brand.addView(b);top.addView(brand,new LinearLayout.LayoutParams(0,dp(62),1));
      TextView gear=t("⚙",25,WHITE);gear.setGravity(Gravity.CENTER);gear.setOnClickListener(v->settings());top.addView(gear,new LinearLayout.LayoutParams(dp(50),dp(62)));root.addView(top);
      ImageView hero=new ImageView(this);hero.setImageResource(com.kurt.motoshop.R.drawable.kurt_brand);hero.setScaleType(ImageView.ScaleType.CENTER_CROP);root.addView(hero,new LinearLayout.LayoutParams(-1,dp(105)));
      body=col();ScrollView sv=new ScrollView(this);sv.addView(body);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);
    }
    TextView title(String s,String sub){TextView a=t(s,29,WHITE);a.setTypeface(null,1);body.addView(a,new LinearLayout.LayoutParams(-1,dp(45)));TextView b=t(sub,13,MUTED);body.addView(b,new LinearLayout.LayoutParams(-1,dp(30)));return a;}
    LinearLayout card(String label,String value,int color,View.OnClickListener click){LinearLayout c=col();c.setPadding(dp(12),dp(8),dp(12),dp(8));c.setBackground(g(PANEL,16,1,color));TextView l=t(label,12,MUTED);TextView v=t(value,24,WHITE);v.setTypeface(null,1);c.addView(l);c.addView(v);c.setOnClickListener(click);return c;}
    void dashboard(){shell("Dashboard");body.setPadding(dp(16),dp(10),dp(16),dp(20));title("Dashboard","Inventory management for KURT MOTOSHOP");
      LinearLayout status=col();status.setPadding(dp(14),dp(8),dp(14),dp(8));status.setBackground(g(Color.rgb(10,22,14),14,1,GREEN));status.addView(t("●  OFFLINE MODE",15,WHITE));status.addView(t("Data is saved on this phone",11,MUTED));body.addView(status,new LinearLayout.LayoutParams(-1,dp(65)));
      LinearLayout stats=new LinearLayout(this);stats.setPadding(0,dp(10),0,dp(5));int pc=db.getInt("pc",0),sc=db.getInt("sc",0);stats.addView(card("PRODUCTS / PARTS",pc+" items",RED,v->products()),new LinearLayout.LayoutParams(0,dp(95),1));stats.addView(card("SERVICES / LABOR",sc+" services",BLUE,v->services()),new LinearLayout.LayoutParams(0,dp(95),1));body.addView(stats);
      addAction("📦","PRODUCTS / PARTS","Brand • Model • Name • Price • Stock",RED,v->products());addAction("🔧","SERVICES / LABOR","Service and labor price list",BLUE,v->services());addAction("＋","ADD PRODUCT","Add brand, model, price and stock",GREEN,v->addProduct());addAction("＋","ADD SERVICE","Add a new labor/service item",ORANGE,v->addService());
      TextView foot=t("KURT MOTOSHOP V.1\nSimple • Offline • Reliable",14,WHITE);foot.setGravity(Gravity.CENTER);foot.setPadding(0,dp(18),0,dp(20));body.addView(foot);
    }
    void addAction(String icon,String name,String sub,int color,View.OnClickListener cl){LinearLayout c=col();c.setPadding(dp(15),dp(10),dp(15),dp(10));c.setBackground(g(PANEL,18,1,color));TextView i=t(icon,28,color);c.addView(i,new LinearLayout.LayoutParams(-1,dp(38)));TextView n=t(name,17,WHITE);n.setTypeface(null,1);c.addView(n);c.addView(t(sub,12,MUTED));TextView ar=t("›",29,WHITE);ar.setGravity(Gravity.RIGHT);c.addView(ar,new LinearLayout.LayoutParams(-1,dp(32)));c.setOnClickListener(cl);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(145));p.setMargins(0,dp(7),0,dp(7));body.addView(c,p);}
    void products(){shell("Products / Parts");body.setPadding(dp(14),dp(8),dp(14),dp(18));title("Products / Parts","Manage your motorcycle parts inventory");EditText search=new EditText(this);search.setHint("Search brand, model or product...");search.setHintTextColor(MUTED);search.setTextColor(WHITE);search.setSingleLine();search.setPadding(dp(14),0,dp(14),0);search.setBackground(g(PANEL,12,1,Color.rgb(55,60,70)));body.addView(search,new LinearLayout.LayoutParams(-1,dp(50)));Button add=new Button(this);add.setText("＋  ADD PRODUCT");add.setTextColor(WHITE);add.setBackground(g(RED,12,0,RED));add.setOnClickListener(v->addProduct());body.addView(add,new LinearLayout.LayoutParams(-1,dp(50)));list=col();body.addView(list);loadProducts();search.addTextChangedListener(new android.text.TextWatcher(){public void beforeTextChanged(CharSequence s,int a,int c,int d){}public void onTextChanged(CharSequence s,int a,int b,int c){loadProducts(s.toString());}public void afterTextChanged(android.text.Editable e){}});}
    void loadProducts(){loadProducts("");} void loadProducts(String q){if(list==null)return;list.removeAllViews();int n=db.getInt("pc",0);for(int i=0;i<n;i++){String br=db.getString("p"+i+"b","");String mo=db.getString("p"+i+"m","");String na=db.getString("p"+i+"n","");String pr=db.getString("p"+i+"p","0");String st=db.getString("p"+i+"s","0");String all=(br+" "+mo+" "+na).toLowerCase();if(!all.contains(q.toLowerCase()))continue;LinearLayout c=col();c.setPadding(dp(14),dp(9),dp(14),dp(9));c.setBackground(g(PANEL,14,1,RED));c.addView(t(br+"  •  "+mo,14,RED));TextView nm=t(na,16,WHITE);nm.setTypeface(null,1);c.addView(nm);c.addView(t("Price: ₱"+pr+"     Stock: "+st,13,MUTED));TextView edit=t("EDIT / DELETE",11,WHITE);edit.setGravity(Gravity.RIGHT);edit.setOnClickListener(v->editProduct(i));c.addView(edit);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(105));p.setMargins(0,dp(6),0,dp(6));list.addView(c,p);}}
    EditText input(String hint){EditText e=new EditText(this);e.setHint(hint);e.setHintTextColor(Color.rgb(120,125,135));e.setTextColor(WHITE);e.setSingleLine();e.setBackground(g(Color.rgb(22,24,29),10,1,Color.rgb(60,65,75)));e.setPadding(dp(12),0,dp(12),0);return e;}
    void addProduct(){LinearLayout f=col();EditText b=input("Brand");EditText m=input("Motorcycle Model");EditText n=input("Product / Part Name");EditText p=input("Price");EditText s=input("Stock Quantity");for(EditText e:new EditText[]{b,m,n,p,s})f.addView(e,new LinearLayout.LayoutParams(-1,dp(50)));AlertDialog d=new AlertDialog.Builder(this).setTitle("Add Product").setView(f).setNegativeButton("Cancel",null).setPositiveButton("SAVE",null).create();d.setOnShowListener(x->d.getButton(-1).setOnClickListener(v->{int i=db.getInt("pc",0);db.edit().putInt("pc",i+1).putString("p"+i+"b",b.getText().toString()).putString("p"+i+"m",m.getText().toString()).putString("p"+i+"n",n.getText().toString()).putString("p"+i+"p",p.getText().toString()).putString("p"+i+"s",s.getText().toString()).apply();d.dismiss();products();}));d.show();}
    void editProduct(int i){new AlertDialog.Builder(this).setTitle("Product #"+(i+1)).setMessage(db.getString("p"+i+"n","")+"\nStock: "+db.getString("p"+i+"s","0")).setNegativeButton("DELETE",(d,w)->{db.edit().putInt("pc",Math.max(0,db.getInt("pc",0)-1)).apply();products();}).setPositiveButton("OK",null).show();}
    void services(){shell("Services / Labor");body.setPadding(dp(14),dp(8),dp(14),dp(18));title("Services / Labor","Manage labor and service pricing");Button add=new Button(this);add.setText("＋  ADD SERVICE");add.setTextColor(WHITE);add.setBackground(g(BLUE,12,0,BLUE));add.setOnClickListener(v->addService());body.addView(add,new LinearLayout.LayoutParams(-1,dp(50)));int n=db.getInt("sc",0);for(int i=0;i<n;i++){LinearLayout c=col();c.setPadding(dp(14),dp(10),dp(14),dp(10));c.setBackground(g(PANEL,14,1,BLUE));c.addView(t(db.getString("s"+i+"n","Service"),16,WHITE));c.addView(t("Labor price: ₱"+db.getString("s"+i+"p","0"),13,MUTED));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(80));p.setMargins(0,dp(6),0,dp(6));body.addView(c,p);}}
    void addService(){LinearLayout f=col();EditText n=input("Service / Labor Name");EditText p=input("Price");f.addView(n,new LinearLayout.LayoutParams(-1,dp(52)));f.addView(p,new LinearLayout.LayoutParams(-1,dp(52)));new AlertDialog.Builder(this).setTitle("Add Service").setView(f).setNegativeButton("Cancel",null).setPositiveButton("SAVE",(d,w)->{int i=db.getInt("sc",0);db.edit().putInt("sc",i+1).putString("s"+i+"n",n.getText().toString()).putString("s"+i+"p",p.getText().toString()).apply();services();}).show();}
    void drawer(){final String[] items={"Dashboard","Products / Parts","Services / Labor","Add Product","Add Service","Settings"};new AlertDialog.Builder(this).setTitle("KURT MOTOSHOP V.1").setItems(items,(d,w)->{if(w==0)dashboard();else if(w==1)products();else if(w==2)services();else if(w==3)addProduct();else if(w==4)addService();else settings();}).show();}
    void settings(){new AlertDialog.Builder(this).setTitle("KURT MOTOSHOP V.1").setMessage("Offline inventory storage\n\nYour products and services are stored locally on this phone.\n\nVersion 1.0").setPositiveButton("OK",null).show();}
}
